apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: 5432
  selector:
    app: postgres