apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: mongodb # Set the name of the deployment
spec:
  replicas: 1 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017 # Exposing the container port 5432 for PostgreSQL client connections.
          volumeMounts:
            - mountPath: /data/db
              name: mongodbdata
      volumes:
        - name: mongodbdata
          persistentVolumeClaim:
            claimName: mongodb-volume-claim
