apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: mongodb-volume # Sets PV name
  labels:
    type: local # Sets PV's type
    app: mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/loic/Documents/Dev/OPA/docker/mongodb/db # Sets PV's host path
    type: Directory
