apiVersion: v1
kind: Service # Create service
metadata:
  name: mongodb-service # Sets the service name
  labels:
    app: mongodb # Defines app to create service for
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017 # Sets the port to run the postgres application
  selector:
    app: mongodb
