version: "3.9"
services:
  fastapi-service:
    image: opa/fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
#    network_mode: "host"
    networks:
      - network1
#    ports:
#      - target: 8000
#        published: 8000
networks:
  network1:
    external: true
    name: my_network
