version: "3.9"
services:
  fastapi:
    image: opa/fastapi:latest
    container_name: fastapi
#    networks:
#      - network1
    ports:
      - target: 8000
        published: 8000
#networks:
#  network1:
#    external: true
#    name: my_network
