# Use postgres/postgres user/password credentials
version: '3.5'


services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      network1:
        ipv4_address: 172.50.0.10

  adminer:
    image: adminer
#    restart: always
    ports:
      - "8080:8080"

networks:
  network1:
    external: true
    name: my_network

volumes:
  postgres-db:
    driver: local
