apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: postgres-volume # Sets PV name
  labels:
    type: local # Sets PV's type
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV's size
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/loic/Documents/Dev/OPA/docker/postgresql/postgres-db"
    type: DirectoryOrCreate
