apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres-service # Sets the service name
  labels:
    app: postgres # Defines app to create service for
spec:
  ports:
    - protocol: TCP
      port: 5432 # Sets the port to run the postgres application
  selector:
    app: postgres
