apiVersion: v1
kind: Service # Create service
metadata:
  name: mongodb-service # Sets the service name
  labels:
    app: mongodb # Defines app to create service for
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
  selector:
    app: mongodb