apiVersion: apps/v1
kind: StatefulSet # Create a deployment
metadata:
  name: mongodb # Set the name of the deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: /data/db
              name: mongodbdata
      volumes:
        - name: mongodbdata
          persistentVolumeClaim:
            claimName: mongodb-volume-claim
