apiVersion: v1
kind: Service # Create service
metadata:
  name: fastapi-service # Sets the service name
  labels:
    app: fastapi # Defines app to create service for
spec:
  type: LoadBalancer # Sets the service type
  ports:
    - protocol: TCP
      port: 8001 # Sets the port to run the postgres application
      targetPort: 8000
  selector:
    app: fastapi