version: "3.5"

services:
  mongodb-service:
    image : mongo:5.0
    container_name: my_mongo
    volumes:
    - ./db:/data/db
    ports:
    - "27017:27017"
    networks:
      - network1

networks:
  network1:
    external: true
    name: my_network
