apiVersion: v1
kind: Service # Create service
metadata:
  name: fastapi-service # Sets the service name
  labels:
    app: fastapi # Defines app to create service for
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      # targetPort: {{ .Values.service.targetPort }}
  selector:
    app: fastapi